// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS95njtJ3fOdUkGYTSLu7dl7cxlCoKhg4',
    appId: '1:1050850706845:web:c6d6ff51fb7fe021b71b74',
    messagingSenderId: '1050850706845',
    projectId: 'aplikasi-catatan-kuliah',
    authDomain: 'aplikasi-catatan-kuliah.firebaseapp.com',
    databaseURL: 'https://aplikasi-catatan-kuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-kuliah.firebasestorage.app',
    measurementId: 'G-KSPQSV9297',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKVgHjDYIBOCsoVh0j-CnL74pML3Nc-c',
    appId: '1:1050850706845:android:f1fe52c56f43e72eb71b74',
    messagingSenderId: '1050850706845',
    projectId: 'aplikasi-catatan-kuliah',
    databaseURL: 'https://aplikasi-catatan-kuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-kuliah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvte9e-YIS8i4ty3Wx_vgvIOLRAGY87xw',
    appId: '1:1050850706845:ios:106db989f16369adb71b74',
    messagingSenderId: '1050850706845',
    projectId: 'aplikasi-catatan-kuliah',
    databaseURL: 'https://aplikasi-catatan-kuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-kuliah.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiCatatanKuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvte9e-YIS8i4ty3Wx_vgvIOLRAGY87xw',
    appId: '1:1050850706845:ios:106db989f16369adb71b74',
    messagingSenderId: '1050850706845',
    projectId: 'aplikasi-catatan-kuliah',
    databaseURL: 'https://aplikasi-catatan-kuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-kuliah.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiCatatanKuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS95njtJ3fOdUkGYTSLu7dl7cxlCoKhg4',
    appId: '1:1050850706845:web:fd9036eab9933ee4b71b74',
    messagingSenderId: '1050850706845',
    projectId: 'aplikasi-catatan-kuliah',
    authDomain: 'aplikasi-catatan-kuliah.firebaseapp.com',
    databaseURL: 'https://aplikasi-catatan-kuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-kuliah.firebasestorage.app',
    measurementId: 'G-HCG2YGTKXZ',
  );
}
